In [1]:
import pandas as pd 
import numpy as np

fb = pd.read_csv("/Users/michalroczek/Desktop/course-files/mrbean_facebook_statuses_with_nulls.csv")
fb.head()

,status_id,status_message,link_name,status_type,status_link,status_published,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys
0,17774451468_10154154735571469,It's time for Mr Bean and Teddy to get ready f...,Mr Bean - Preparing To Go Camping,video,https://youtu.be/fgURU75gTMQ,2016-06-23 11:35:48,16570.0,223.0,338.0,16079,166,6,320,0,0
1,17774451468_10154146584106469,NaN,Timeline Photos,photo,https://www.facebook.com/MrBean/photos/a.10150...,2016-06-21 10:00:01,119886.0,2171.0,1657.0,114008,946,104,4795,16,17
2,17774451468_10154135502911469,NaN,Timeline Photos,photo,https://www.facebook.com/MrBean/photos/a.10150...,2016-06-19 10:00:01,NaN,2395.0,10050.0,218579,2988,188,13992,52,53
3,17774451468_10154138120151469,Mr Bean is ready to do some shopping but bewar...,www.youtube.com,video,https://www.youtube.com/watch?v=58Z8J0PbLS8,2016-06-18 11:00:02,20913.0,214.0,257.0,20338,211,20,336,0,8
4,17774451468_10154135502476469,NaN,Timeline Photos,photo,https://www.facebook.com/MrBean/photos/a.10150...,2016-06-17 09:00:01,223602.0,880.0,2228.0,215591,2872,259,4814,27,39

In [2]:
fb.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   status_id         56 non-null     object
 1   status_message    40 non-null     object
 2   link_name         56 non-null     object
 3   status_type       56 non-null     object
 4   status_link       56 non-null     object
 5   status_published  56 non-null     object
 6   num_reactions     54 non-null     float64
 7   num_comments      55 non-null     float64
 8   num_shares        56 non-null     float64
 9   num_likes         56 non-null     int64
 10  num_loves         56 non-null     int64
 11  num_wows          56 non-null     int64
 12  num_hahas         56 non-null     int64
 13  num_sads          56 non-null     int64
 14  num_angrys        56 non-null     int64
dtypes: float64(3), int64(6), object(6)
memory usage: 34.4 KB

In [3]:
fb_new = pd.read_csv("/Users/michalroczek/Desktop/course-files/mrbean_facebook_statuses_with_nulls.csv", usecols=['status_message','status_type','link_name','num_reactions','num_shares','num_likes'])

In [4]:
fb_new.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   status_message  40 non-null     object
 1   link_name       56 non-null     object
 2   status_type     56 non-null     object
 3   num_reactions   54 non-null     float64
 4   num_shares      56 non-null     float64
 5   num_likes       56 non-null     int64
dtypes: float64(2), int64(1), object(3)
memory usage: 16.1 KB

In [6]:
#How many rows are in our object
len(fb_new)

56

In [8]:
fb_new['status_type'].nunique()

3

In [9]:
fb_new['status_type'].value_counts()

video    32
photo    22
link      2
Name: status_type, dtype: int64

In [12]:
fb_new['status_type'] = fb_new['status_type'].astype('category')

In [13]:
fb_new.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   status_message  40 non-null     object
 1   link_name       56 non-null     object
 2   status_type     56 non-null     category
 3   num_reactions   54 non-null     float64
 4   num_shares      56 non-null     float64
 5   num_likes       56 non-null     int64
dtypes: category(1), float64(2), int64(1), object(2)
memory usage: 13.0 KB

In [16]:
fb_new['link_name'].value_counts()

Timeline Photos                                                               22
www.youtube.com                                                                4
Rowan Atkinson: I will never wave goodbye to Mr Bean                           1
Mr Bean - Crazy Golf                                                           1
Mr. Bean - Shopping for Towels                                                 1
Mr. Bean (NEW series) - Ice Cream                                              1
Mr Bean - Broken Tooth                                                         1
Mr. Bean - Saxophone Player                                                    1
Mr Bean - Country fete games -- Volksfest Spiele                               1
Mr. Bean's Happy Moments                                                       1
Mr. Bean - High Dive                                                           1
Mr. Bean - Embarrassing Moments Compilation                                    1
Mr Bean - Prison Break                                                         1
Mr Bean - Ray Of Sunshine                                                      1
Mr. Bean (NEW series) - The Lift                                               1
Mr. Bean - Making A Sandwich                                                   1
Mr Bean - Chemistry experiment                                                 1
Mr. Bean - Counting Sheep.                                                     1
Mr Bean - Restaurant Etiquette                                                 1
Mr. Bean - Fixing Your Own Teeth                                               1
Mr Bean - Dinner for Two                                                       1
Mr. Bean - How to stop a baby from crying                                      1
Mr Bean - Sun Block                                                            1
Mr. Bean - Sneezing and Snoozing In Church                                     1
Mr. Bean - Elderly people on stairs                                            1
Mr. Bean - At the Disco                                                        1
Mr. Bean - Alarm Clock                                                         1
Mr Bean - Preparing To Go Camping                                              1
Mr Bean (NEW series) - Litterbugs Clip                                         1
Mr. Bean - Mystery creature                                                    1
Mr. Bean (NEW Series) - Dancing Bean                                           1
Even in LEGO, Mr. Bean travels in comfort | The Brothers Brick | LEGO Blog     1
Name: link_name, dtype: int64

In [17]:
fb_new['link_name'] = fb_new['link_name'].astype('category')

In [18]:
fb_new.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   status_message  40 non-null     object
 1   link_name       56 non-null     category
 2   status_type     56 non-null     category
 3   num_reactions   54 non-null     float64
 4   num_shares      56 non-null     float64
 5   num_likes       56 non-null     int64
dtypes: category(2), float64(2), int64(1), object(1)
memory usage: 12.6 KB

In [19]:
fb_new.head()

,status_message,link_name,status_type,num_reactions,num_shares,num_likes
0,It's time for Mr Bean and Teddy to get ready f...,Mr Bean - Preparing To Go Camping,video,16570.0,338.0,16079
1,NaN,Timeline Photos,photo,119886.0,1657.0,114008
2,NaN,Timeline Photos,photo,NaN,10050.0,218579
3,Mr Bean is ready to do some shopping but bewar...,www.youtube.com,video,20913.0,257.0,20338
4,NaN,Timeline Photos,photo,223602.0,2228.0,215591

In [21]:
fb_new['num_reactions'].replace(np.NaN,0,inplace=True) 
fb_new['num_shares'].replace(np.NaN,0,inplace=True)

In [22]:
fb_new.head()

,status_message,link_name,status_type,num_reactions,num_shares,num_likes
0,It's time for Mr Bean and Teddy to get ready f...,Mr Bean - Preparing To Go Camping,video,16570.0,338.0,16079
1,NaN,Timeline Photos,photo,119886.0,1657.0,114008
2,NaN,Timeline Photos,photo,0.0,10050.0,218579
3,Mr Bean is ready to do some shopping but bewar...,www.youtube.com,video,20913.0,257.0,20338
4,NaN,Timeline Photos,photo,223602.0,2228.0,215591

In [23]:
fb_new.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   status_message  40 non-null     object
 1   link_name       56 non-null     category
 2   status_type     56 non-null     category
 3   num_reactions   56 non-null     float64
 4   num_shares      56 non-null     float64
 5   num_likes       56 non-null     int64
dtypes: category(2), float64(2), int64(1), object(1)
memory usage: 12.6 KB

In [25]:
fb_new['num_reactions'] = fb_new['num_reactions'].astype('int')
fb_new['num_shares'] = fb_new['num_shares'].astype('int')
fb_new['num_likes'] = fb_new['num_likes'].astype('int')

In [26]:
fb_new.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   status_message  40 non-null     object
 1   link_name       56 non-null     category
 2   status_type     56 non-null     category
 3   num_reactions   56 non-null     int64
 4   num_shares      56 non-null     int64
 5   num_likes       56 non-null     int64
dtypes: category(2), int64(3), object(1)
memory usage: 12.6 KB

In [27]:
fb_new

,status_message,link_name,status_type,num_reactions,num_shares,num_likes
0,It's time for Mr Bean and Teddy to get ready f...,Mr Bean - Preparing To Go Camping,video,16570,338,16079
1,NaN,Timeline Photos,photo,119886,1657,114008
2,NaN,Timeline Photos,photo,0,10050,218579
3,Mr Bean is ready to do some shopping but bewar...,www.youtube.com,video,20913,257,20338
4,NaN,Timeline Photos,photo,223602,2228,215591
5,Mr. Bean's sweet treat causes him pain!,Mr Bean - Broken Tooth,video,24742,448,23977
6,Mr Bean's chasing a ray of sunshine!\r\nhttps:...,Mr Bean - Ray Of Sunshine,video,21886,471,21246
7,Mr Bean is enjoying the sunshine....that is un...,Mr Bean - Sun Block,video,22015,546,21293
8,NaN,Timeline Photos,photo,196913,9849,190476
9,NaN,Timeline Photos,photo,196366,5378,190857
10,Mr Bean competes with a Royal Guard. Can he b...,www.youtube.com,video,30109,905,28906
11,NaN,Timeline Photos,photo,233121,3423,218235
12,HAPPY GEEK PRIDE DAY! Watch Mr Bean's geeky mo...,Mr Bean - Chemistry experiment,video,0,1447,26498
13,Cooking Sunday lunch? Here's how not to do it!...,Mr Bean - Dinner for Two,video,19154,588,18491
14,NaN,Timeline Photos,photo,167980,3695,157505
15,Mr Bean shows you how to get that all importan...,www.youtube.com,video,12179,194,11824
16,Having sleeping troubles? Let Mr. Bean show yo...,www.youtube.com,video,11419,325,11007
17,NaN,Timeline Photos,photo,272955,6584,258111
18,Happy Mother's Day! Aren't you glad Mr. Bean'...,Mr. Bean - How to stop a baby from crying,video,48030,2395,45624
19,Brand New Friday Fun! \r\nWill Mr Bean get his...,Timeline Photos,photo,58541,1734,56140
20,Relive the very best of Mr. Bean's very worst ...,Mr. Bean - Embarrassing Moments Compilation,video,28539,1931,26821
21,It's International Dance Day! Mr Bean has got ...,Mr. Bean (NEW Series) - Dancing Bean,video,22619,516,22036
22,Caption this...,Timeline Photos,photo,299330,6443,287368
23,"Monday mornings, Mr. Bean style!\r\nhttps://ww...",Mr. Bean - Alarm Clock,video,34144,1878,32687
24,Happy Earth Day! Mr Bean is doing his bit to l...,Mr Bean (NEW series) - Litterbugs Clip,video,29631,794,28880
25,NaN,Timeline Photos,photo,305983,7561,296668
26,NaN,Timeline Photos,photo,133245,2286,128606
27,Mr. Bean demonstrates the correct etiquette wh...,Mr Bean - Restaurant Etiquette,video,25504,575,24409
28,NaN,Timeline Photos,photo,331512,19652,318173
29,Warning: Don't try this at home!\r\nhttps://ww...,Mr. Bean - Fixing Your Own Teeth,video,39186,2106,37247
30,Happy Golfer's Day! Fancy some golfing tips fr...,Mr Bean - Crazy Golf,video,11564,886,10951
31,NaN,Timeline Photos,photo,470129,18989,451036
32,Summer is coming and you know what that means…...,Mr. Bean (NEW series) - Ice Cream,video,18682,614,18154
33,"Mr. Bean tries, before he buys! \r\nhttps://ww...",Mr. Bean - Shopping for Towels,video,24096,1684,22888
34,NaN,Timeline Photos,photo,72606,1835,70388
35,NaN,Timeline Photos,photo,136609,2943,131976
36,What could it be…?\r\nhttps://www.youtube.com/...,Mr. Bean - Mystery creature,video,16370,526,15887
37,Mr. Bean's unusual way of changing his money.\...,Mr. Bean - Saxophone Player,video,17157,1194,16411
38,Did you find all 11 easter eggs? HAPPY EASTER!!,Timeline Photos,photo,94598,2390,92290
39,Teddy has hidden 11 easter eggs but Mr Bean ca...,Timeline Photos,photo,15312,939,14838
40,"When a simple ""excuse me"" won't do!\r\nhttps:/...",Mr. Bean - Elderly people on stairs,video,26237,1684,25079
41,Rowan Atkinson officially says he will never w...,Rowan Atkinson: I will never wave goodbye to M...,link,98365,2581,94349
42,It's International Day of Happiness today! Spr...,Mr. Bean's Happy Moments,video,232440,41910,212499
43,Mr Bean was ahead of his time with his dance m...,Mr. Bean - At the Disco,video,16863,6,15987
44,NaN,Timeline Photos,photo,144332,5744,141303
45,NaN,Timeline Photos,photo,282389,19375,266105
46,Happy Napping Day! Mr. Bean always makes time ...,Mr. Bean - Sneezing and Snoozing In Church,video,19254,1526,18370
47,Happy Friday!,Timeline Photos,photo,325558,11754,313017
48,Its Pack Your Lunch Day!!! Mr Bean has made hi...,Mr. Bean - Making A Sandwich,video,29120,3607,27500
49,A different twist on a classic sleeping method...,Mr. Bean - Counting Sheep.,video,19725,1489,18847
50,What score out of 10 would you award Mr Bean f...,Mr. Bean - High Dive,video,25261,1715,23946
51,Happy Friday!!,Timeline Photos,photo,285043,21857,274426
52,Mr Bean and Teddy learn a valuable lesson abou...,Mr. Bean (NEW series) - The Lift,video,18379,481,17896
53,"Mr. Bean is having fun at the Country Fete, no...",Mr Bean - Country fete games -- Volksfest Spiele,video,30285,2010,28857
54,Look at this AMAZING Mr. Bean made out of Lego...,"Even in LEGO, Mr. Bean travels in comfort | Th...",link,31377,1145,29372
55,Watch Mr Bean plan his great escape…\r\nhttps:...,Mr Bean - Prison Break,video,22559,688,21741